#Expyriment  (Revision ; Python 2.7.3), .xpe-file
#date: Fri Mar 28 2014 18:40:00
#display: size=(800, 600), window_mode=True, opengl=False
#os: ('Linux', 'is146569', '3.2.0-60-generic', '#91-Ubuntu SMP Wed Feb 19 03:54:44 UTC 2014', 'x86_64', 'x86_64')
Time,Type,Event,Value,Detail,Detail2
335,stderr,received,'Traceback (most recent call last):'
335,stderr,received,'  File "./display_pictures.py", line 43, in <module>'
335,stderr,received,'    stim = stimuli.Picture(path)'
335,stderr,received,'  File "/usr/local/lib/python2.7/dist-packages/expyriment/stimuli/_picture.py", line 52, in __init__'
335,stderr,received,'    filename))'
336,stderr,received,"IOError: The picture file 'forMathfonts/img23.png' does not exist"
