#Expyriment  (Revision ; Python 2.7.3), .xpe-file
#date: Fri Mar 28 2014 18:39:43
#display: size=(800, 600), window_mode=True, opengl=False
#os: ('Linux', 'is146569', '3.2.0-60-generic', '#91-Ubuntu SMP Wed Feb 19 03:54:44 UTC 2014', 'x86_64', 'x86_64')
Time,Type,Event,Value,Detail,Detail2
322,stderr,received,'Traceback (most recent call last):'
322,stderr,received,'  File "./display_pictures.py", line 43, in <module>'
322,stderr,received,'    stim = stimuli.Picture(path)'
322,stderr,received,'  File "/usr/local/lib/python2.7/dist-packages/expyriment/stimuli/_picture.py", line 52, in __init__'
323,stderr,received,'    filename))'
323,stderr,received,"IOError: The picture file '$$y+\\sin (x)$$' does not exist"
